stages:
  - build-app
  - build-image
  - render-charts

default:
  tags:
    - ${ENVIRONMENT}-runner

include:
  - file: /build-image/template.yml
    project: capstan/pow/gitlab-templates
    ref: build-image-v3.0.4

  - file: /render-charts/template.yml
    project: capstan/pow/gitlab-templates
    ref: render-charts-v3

variables:
  APP_NAME: artstor-ui
  APP_SERVICE_NAME: artstor-ui
  EUREKA_SERVICE_NAME: artstor-ui
  PIPELINE:
    description: "Choose pipeline"
    value: ""
    options:
      - "deploy"
      - ""
  ENVIRONMENT:
    description: "Choose environment"
    value: "test"
    options:
      - "test"
      - "prod"
  APP_IMAGE: docker-virtual.artifactory.acorn.cirrostratus.org/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  HELM_CHART_PATH: $CI_PROJECT_DIR/k8s/chart
  MANIFEST_OUTPUT_DIRECTORY: $CI_PROJECT_DIR/manifests

build-app:
  stage: build-app
  image: docker-virtual.artifactory.acorn.cirrostratus.org/node:11.0.0
  script:
    - yarn install
    - yarn build:ssr:$ENVIRONMENT
  rules:
    - if: $PIPELINE == 'deploy'
      when: always
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/

build-image:
  stage: build-image
  extends: .build-image
  needs:
    - job: build-app
      artifacts: true
  rules:
    - if: $PIPELINE == 'deploy'
      when: on_success
  variables:
    CONTEXT: .
    DOCKERFILE: Dockerfile
    IMAGE_TAG: artifactory.acorn.cirrostratus.org/artstor-air-node:$CI_COMMIT_SHORT_SHA
    EXTRA_ARGS: --build-arg SAGOKU_ENV=$ENVIRONMENT

render-charts:
  stage: render-charts
  extends: .render-charts