stages:
  - build
  - deploy

default:
  tags:
    - ${ENVIRONMENT}-runner

include:
  - file: /build-image/template.yml
    project: capstan/pow/gitlab-templates
    ref: build-image-v3

  - file: /render-charts/template.yml
    project: capstan/pow/gitlab-templates
    ref: render-charts-v3

  - file: /run-argo-deployer/template.yml
    project: capstan/pow/gitlab-templates
    ref: run-argo-deployer-v3

variables:
  APP_NAME: artstor-ui
  APP_SERVICE_NAME: artstor-ui
  EUREKA_SERVICE_NAME: artstor-ui
  PIPELINE:
    description: "Choose pipeline"
    value: ""
    options:
      - "deploy"
      - ""
  ENVIRONMENT:
    description: "Choose environment"
    value: "test"
    options:
      - "test"
      - "prod"
  APP_IMAGE: docker-virtual.artifactory.acorn.cirrostratus.org/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  HELM_CHART_PATH: "https://artifactory.acorn.cirrostratus.org/artifactory/helm-local/capstan-app/capstan-app.tgz:1.9.1"
  MANIFEST_OUTPUT_DIRECTORY: $CI_PROJECT_DIR/manifests

build-app:
  stage: build
  image: docker-virtual.artifactory.acorn.cirrostratus.org/node:11.0.0
  script:
    - yarn install
    - yarn build:ssr:$ENVIRONMENT
  rules:
    - if: $PIPELINE == 'deploy'
      when: always
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/

build-image:
  stage: build
  extends: .build-image
  needs:
    - job: build-app
      artifacts: true
  rules:
    - if: $PIPELINE == 'deploy'
      when: on_success
  variables:
    CONTEXT: .
    DOCKERFILE: Dockerfile
    IMAGE_TAG: $APP_IMAGE
    EXTRA_ARGS: --build-arg SAGOKU_ENV=$ENVIRONMENT

render-charts:
  stage: build
  extends: .render-charts
  rules:
    - if: $PIPELINE == 'deploy'
      when: on_success

deploy:
  stage: deploy
  extends: .run-argo-deployer
  rules:
    - if: $PIPELINE == 'deploy'
      when: on_success
  variables:
    ACTION: deploy
    APP_NAME: $APP_NAME
    ENVIRONMENT: $ENVIRONMENT
    GROUP_NAME: $ITHAKA_OWNER
    INPUT_FILES_LOCATION: manifests
