stages:
    - build

default:
    tags:
        - ${ENVIRONMENT}-runner

include:
    - project: capstan/pow/gitlab-templates
      file: /static-app-deployer/template.yml
      ref: static-app-deployer-v1

variables:
    APP_NAME: artstor-ui
    PIPELINE: "deploy"
    ENVIRONMENT:
      value: "test"
      description: "Select ENVIRONMENT"
      options:
        - "test"
        - "prod"

build:
    stage: build
    extends: .build-static-app
    image: docker-virtual.artifactory.acorn.cirrostratus.org/node:11.0.0
    before_script:
        - chmod +x $CI_PROJECT_DIR/build.sh
    variables:
        BUILD_SCRIPT_PATH: $CI_PROJECT_DIR/build.sh
        BUILD_OUTPUT_PATH: $CI_PROJECT_DIR/dist/
        OTHER_ARGS: $ENVIRONMENT
    rules:
        - if: $PIPELINE == 'deploy'
          when: always