version: '3'
services:
  labs_blazegraph:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - "80:8080"
    - "8080:8080"
    - "443:443"
    environment:
      SGK_APP: "${SGK_APP}"
      SGK_APP_SERVICE_NAME: "${SGK_APP_SERVICE_NAME}"
      SGK_APP_TYPE: "${SGK_APP_TYPE}"
      SGK_APP_USER: "${SGK_APP_USER}"
      SGK_DEPLOY_ID: "${SGK_DEPLOY_ID}"
      SGK_BASE_DOMAIN: "${SGK_BASE_DOMAIN}"
      SGK_ENVIRONMENT: "${SGK_ENVIRONMENT}"
      SGK_HEALTHCHECK_SERVICE: "${SGK_HEALTHCHECK_SERVICE}"
      SGK_WITH_EUREKA_SIDE_CAR: "${SGK_WITH_EUREKA_SIDE_CAR}"
      SGK_APP_PACKAGE_VERSION: "${SGK_APP_PACKAGE_VERSION}"
      SGK_VPC_ENABLED: "${SGK_VPC_ENABLED}"